[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'std=lib/forge-std/src/', '@openzeppelin=lib/openzeppelin-contracts', "base64-sol=lib/base64"]

# See more config options https://github.com/gakonst/foundry/tree/master/config